# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache/cache_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cache/cache_service.proto',
  package='cache_transport',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x63\x61\x63he/cache_service.proto\x12\x0f\x63\x61\x63he_transport\x1a\x19google/protobuf/any.proto\"1\n\nCacheQuery\x12#\n\x05query\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"K\n\x12\x43\x61\x63heQueryResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12&\n\x08response\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"\x0c\n\nCacheStats\"A\n\x12\x43\x61\x63heStatsResponse\x12+\n\rcurrent_stats\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any2\xa8\x01\n\x0c\x43\x61\x63heService\x12K\n\x05Query\x12\x1b.cache_transport.CacheQuery\x1a#.cache_transport.CacheQueryResponse\"\x00\x12K\n\x05Stats\x12\x1b.cache_transport.CacheStats\x1a#.cache_transport.CacheStatsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_CACHEQUERY = _descriptor.Descriptor(
  name='CacheQuery',
  full_name='cache_transport.CacheQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='cache_transport.CacheQuery.query', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=122,
)


_CACHEQUERYRESPONSE = _descriptor.Descriptor(
  name='CacheQueryResponse',
  full_name='cache_transport.CacheQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='found', full_name='cache_transport.CacheQueryResponse.found', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='cache_transport.CacheQueryResponse.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=199,
)


_CACHESTATS = _descriptor.Descriptor(
  name='CacheStats',
  full_name='cache_transport.CacheStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=213,
)


_CACHESTATSRESPONSE = _descriptor.Descriptor(
  name='CacheStatsResponse',
  full_name='cache_transport.CacheStatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_stats', full_name='cache_transport.CacheStatsResponse.current_stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=280,
)

_CACHEQUERY.fields_by_name['query'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_CACHEQUERYRESPONSE.fields_by_name['response'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_CACHESTATSRESPONSE.fields_by_name['current_stats'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['CacheQuery'] = _CACHEQUERY
DESCRIPTOR.message_types_by_name['CacheQueryResponse'] = _CACHEQUERYRESPONSE
DESCRIPTOR.message_types_by_name['CacheStats'] = _CACHESTATS
DESCRIPTOR.message_types_by_name['CacheStatsResponse'] = _CACHESTATSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CacheQuery = _reflection.GeneratedProtocolMessageType('CacheQuery', (_message.Message,), {
  'DESCRIPTOR' : _CACHEQUERY,
  '__module__' : 'cache.cache_service_pb2'
  # @@protoc_insertion_point(class_scope:cache_transport.CacheQuery)
  })
_sym_db.RegisterMessage(CacheQuery)

CacheQueryResponse = _reflection.GeneratedProtocolMessageType('CacheQueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _CACHEQUERYRESPONSE,
  '__module__' : 'cache.cache_service_pb2'
  # @@protoc_insertion_point(class_scope:cache_transport.CacheQueryResponse)
  })
_sym_db.RegisterMessage(CacheQueryResponse)

CacheStats = _reflection.GeneratedProtocolMessageType('CacheStats', (_message.Message,), {
  'DESCRIPTOR' : _CACHESTATS,
  '__module__' : 'cache.cache_service_pb2'
  # @@protoc_insertion_point(class_scope:cache_transport.CacheStats)
  })
_sym_db.RegisterMessage(CacheStats)

CacheStatsResponse = _reflection.GeneratedProtocolMessageType('CacheStatsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CACHESTATSRESPONSE,
  '__module__' : 'cache.cache_service_pb2'
  # @@protoc_insertion_point(class_scope:cache_transport.CacheStatsResponse)
  })
_sym_db.RegisterMessage(CacheStatsResponse)



_CACHESERVICE = _descriptor.ServiceDescriptor(
  name='CacheService',
  full_name='cache_transport.CacheService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=283,
  serialized_end=451,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='cache_transport.CacheService.Query',
    index=0,
    containing_service=None,
    input_type=_CACHEQUERY,
    output_type=_CACHEQUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Stats',
    full_name='cache_transport.CacheService.Stats',
    index=1,
    containing_service=None,
    input_type=_CACHESTATS,
    output_type=_CACHESTATSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CACHESERVICE)

DESCRIPTOR.services_by_name['CacheService'] = _CACHESERVICE

# @@protoc_insertion_point(module_scope)
