# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.transport.proto.cache import cache_service_pb2 as cache_dot_cache__service__pb2


class CacheServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/cache_transport.CacheService/Query',
                request_serializer=cache_dot_cache__service__pb2.CacheQuery.SerializeToString,
                response_deserializer=cache_dot_cache__service__pb2.CacheQueryResponse.FromString,
                )
        self.Stats = channel.unary_unary(
                '/cache_transport.CacheService/Stats',
                request_serializer=cache_dot_cache__service__pb2.CacheStats.SerializeToString,
                response_deserializer=cache_dot_cache__service__pb2.CacheStatsResponse.FromString,
                )


class CacheServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Send one text input and receive a boolean response whether it passed the filter or not
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=cache_dot_cache__service__pb2.CacheQuery.FromString,
                    response_serializer=cache_dot_cache__service__pb2.CacheQueryResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=cache_dot_cache__service__pb2.CacheStats.FromString,
                    response_serializer=cache_dot_cache__service__pb2.CacheStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cache_transport.CacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CacheService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache_transport.CacheService/Query',
            cache_dot_cache__service__pb2.CacheQuery.SerializeToString,
            cache_dot_cache__service__pb2.CacheQueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache_transport.CacheService/Stats',
            cache_dot_cache__service__pb2.CacheStats.SerializeToString,
            cache_dot_cache__service__pb2.CacheStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
